### PR TITLE
add flex layout at social cards

### PR DESCRIPTION
**Pull request by PhilippDemmelmair**
Could anyone review pls?

### CODE REVIEW

**Review by desplodur — APPROVED** [review]

**Comment by desplodur** [comment]
lgtm

**Review by dananhsl — APPROVED** [review]
Lgtm! well done

**Comment by PhilippDemmelmair** [comment]
> Lgtm! well done

thx

**Comment by PhilippDemmelmair** [comment]
> lgtm

thx

**Pull request merged**
